# Frontend only
version: "0.1"

global:
  setup:
    - npm ci
    - cp -r examples frontend/src/assets/examples
pipeline:
  runTest:
    exec:
      - npm run coverage
    settings:
      workingDir: frontend
settings:
  exportFunctionOrClass: allow
  include:
      - frontend
  # Location of the test files
  testPlacementStrategies:
    - type: centralized
      testFilePattern: "{{sourceFileName}}.ts"
